image: eclipse-temurin:17

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_BUILD_REF_NAME}"
  PROJECTNAME: osuWikiPreview

before_script:
  - java -version
  - chmod -R 755 ./*
  - cd ${PROJECTNAME}
  - ls -l

stages:
  - check
  - compile
  - javadoc

endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

trycatch:
  allow_failure: true
  script: curl ${SERVER}ci/trycatch.sh | bash
  stage: check
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

spotbugs:
  allow_failure: true
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :spotbugsMain
    - mv ./build/reports/spotbugs/main/spotbugs.html ../spotbugs.html
  stage: check
  artifacts:
    name: "SpotBugs Report"
    expire_in: 1 week
    when: always
    paths:
      - spotbugs.html

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script: curl ${SERVER}ci/documentation.sh | bash
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

compile:
  script: curl ${SERVER}ci/publish.sh | bash
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}.jar